version: '2.2'
services:
  gluetun:
      image: qmcgaw/gluetun:v3.32
      container_name: gluetun
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun
      ports:
        - 8888:8888/tcp
        - 8388:8388/tcp
        - 8388:8388/udp
        - ${WEBUI_PORT}:${WEBUI_PORT}
      volumes:
        - ./data/gluetun:/gluetun
      environment:
        #https://mullvad.net/en/account/#/create/
        #https://github.com/qdm12/gluetun/wiki/Mullvad
        - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
        - VPN_TYPE=${VPN_TYPE}
        - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
        - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
        - SERVER_CITIES=${SERVER_CITIES}
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "10"
      restart: always

  plex:
    image: linuxserver/plex:1.29.2
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} #https://www.plex.tv/claim
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/cache:/cache
      - ./downloads:/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always

  torrent:
    restart: always
    container_name: torrent
    network_mode: "service:gluetun"
    image: linuxserver/qbittorrent:4.4.1
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ./downloads:/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
